on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Otimizado com Cache - Acao 3
        run: |
          # Define o nome da imagem e converte para minúsculo
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')

          # 1. Tenta baixar a imagem existente para usar como cache [cite: 116, 123]
          docker pull $IMAGE_ID:latest || true

          # 2. Build usando cache-from e BuildKit Inline Cache [cite: 118, 124, 125]
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from $IMAGE_ID:latest \
            -t $IMAGE_ID:${{ github.sha }} \
            -t $IMAGE_ID:latest .

          # 3. Push das novas imagens atualizadas [cite: 121, 122]
          docker push $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:latest